work_dir: ./search_run/run/work_dir/ntu/xview/agcn_joint_Srch_CTN
model_saved_name: ./search_run/run/runs/ntu_cv_agcn_joint_Srch_CTN
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu/xview/train_data_joint.npy
  label_path: ./data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False
test_feeder_args:
  data_path: ./data/ntu/xview/val_data_joint.npy
  label_path: ./data/ntu/xview/val_label.pkl

# model
model: model.agcn_search.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 45, 60]

# training
device: [0]
start_epoch: 0
batch_size: 40
test_batch_size: 20
num_epoch: 70
nesterov: True
