# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu/xview/val_data_joint.npy
  label_path: ./data/ntu/xview/val_label.pkl
  debug: False

# model
#Reduce model
#model: model.agcn2.Model2 
#model CT
#model: model.agcn.Model 
#Searched model
model: model.agcn3.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: [0,1,2,3]
test_batch_size: 40
weights: ./runs/ntu_cv_agcn_joint_Srch_CT-59-28200.pt

work_dir: ./work_dir/ntu/xview/agcn_test_joint
model_saved_name: ./runs/ntu_cv_agcn_test_joint
save_score: True