# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu/xview/val_data_bone.npy
  label_path: ./data/ntu/xview/val_label.pkl
  debug: False

# model
#Reduce model
#model: model.agcn2.Model2 
#model CT
#model: model.agcn.Model 
#Searched model
model: model.agcn3.Model

model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: [0,1,2,3]
test_batch_size: 40
#weights: ./runs/ntu_cv_agcn_bone_C3-69-27440.pt
#weights: ./runs/ntu_cv_agcn_bone_TT-65-25872.pt #53
#weights: ./runs/ntu_cv_agcn_bone_ReK2-51-24440.pt #94.42
weights: ./runs/ntu_cv_agcn_bone_Srch_CT-57-22736.pt

work_dir: ./work_dir/ntu/xview/agcn_test_bone
model_saved_name: ./runs/ntu_cv_agcn_test_bone
save_score: True