work_dir: ./work_dir/ntu/xview/agcn_bothBM
model_saved_name: ./runs/ntu_cv_agcn_bothBM
# feeder
feeder: feeders.feederBoth.Feeder
train_feeder_args:
  #data_path1: ./data/ntu/xview/train_data_joint.npy
  #data_path2: ./data/ntu/xview/train_data_bone.npy
  #data_path2: ./data/ntu/xview/train_data_joint_motion.npy
  data_path1: ./data/ntu/xview/train_data_bone.npy
  data_path2: ./data/ntu/xview/train_data_bone_motion.npy
  label_path: ./data/ntu/xview/train_label.pkl
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 270
  normalization: False

test_feeder_args:
  #data_path1: ./data/ntu/xview/val_data_joint.npy
  data_path1: ./data/ntu/xview/val_data_bone.npy
  data_path2: ./data/ntu/xview/val_data_bone_motion.npy
  label_path: ./data/ntu/xview/val_label.pkl

# model
model: model.agcn2.Model3
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005
base_lr: 0.1
step: [30, 45, 60]

# training
device: [0, 1 ,2, 3]
batch_size: 48
test_batch_size: 24
num_epoch: 70
nesterov: True

